//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorQitService
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacancyEmployee
    {
        public int matchID { get; set; }
        public int employeeID { get; set; }
        public int vacancyID { get; set; }
        public int rating { get; set; }
        public int matchingValue { get; set; }
        public string reaction { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Vacancy Vacancy { get; set; }
    }
}
